// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    mainSidebar: [
        {
            type: 'doc',
            id: 'architecture/index', // Matches docs/architecture/index.md
            label: 'Getting Started',
        },
        {
            type: 'category',
            label: 'Architecture & Guides',
            collapsed: false,
            items: [
                'architecture/directory-structure', // Matches docs/architecture/directory-structure.md
            ],
        },
        {
            type: 'category',
            label: 'Architecture Decision Records',
            collapsed: true,
            link: {
                type: 'doc',
                id: 'adr/index'
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'adr', // Dynamically loads all files from docs/adr/
                },
            ],
        },
    ],
};

export default sidebars;